const disposableDomains = new Set([
  "mailinator.com", "guerrillamail.com", "tempmail.com", "temp-mail.org",
  "throwaway.email", "0-mail.com", "10minutemail.com", "20minutemail.com",
  "30minutemail.com", "anonaddy.com", "anonymail.net", "boun.cr",
  "bx-zone.com", "chacuo.net", "cool.fr.nf", "correotemporal.org",
  "courriel.fr.nf", "dispostable.com", "emailondeck.com", "emailtemporario.com.br",
  "emailtmp.com", "emz.net", "enayu.com", "fakeinbox.com", "fake-mail.net",
  "filzmail.com", "getairmail.com", "getnada.com", "guerrillamail.net",
  "guerrillamail.org", "harakirimail.com", "hotmailproduct.com", "inboxalias.com",
  "inboxbear.com", "inboxkitten.com", "ipn.vc", "jetable.com", "jetable.net",
  "jetable.org", "lags.us", "mail-temp.com", "mail0.com", "mail138.com",
  "mail4trash.com", "mailcatch.com", "maildrop.cc", "maildu.de", "maildx.com",
  "maileater.com", "mailexpire.com", "mailfa.tk", "mailforspam.com",
  "mailfreeonline.com", "mailincubator.com", "mailinator2.com", "mailmetrash.com",
  "mailmoat.com", "mailnator.com", "mailnesia.com", "mailnull.com",
  "mailpick.biz", "mailprotech.com", "mailscrap.com", "mailshell.com",
  "mailtemp.net", "mailsucker.net", "mailtothis.com", "mailtrash.net",
  "mailyzer.com", "mbx.cc", "mega.zik.dj", "mintemail.com", "moncourrier.fr.nf",
  "monemail.fr.nf", "mt2009.com", "mycleaninbox.net", "myemail.xyz",
  "mypartyclip.de", "mytrashmail.com", "nekoinbox.com", "neverbox.com",
  "nobulk.com", "nopam.net", "nospam.ze.tc", "nowmymail.com", "objectmail.com",
  "odnorazovoe.ru", "oneoffemail.com", "oopi.org", "ovpn.to", "pookmail.com",
  "proxymail.eu", "putthisinyourspamdatabase.com", "quickinbox.com",
  "rcpt.at", "receive-sms.cc", "receive-sms-online.info", "receive-sms.cellbet.com",
  "receive-sms.com", "receive-sms.no", "receive-sms-server.com", "receive-sms.us",
  "recruitaware.com", "regbypass.com", "remove-this.com", "safetymail.info",
  "sandelf.de", "scryptmail.com", "selfdestructingmail.com", "send22u.info",
  "sharpmail.co.uk", "shitmail.de", "shitmail.org", "showme.social",
  "slopsbox.com", "sneakemail.com", "sogetthis.com", "soodonims.com",
  "spambog.com", "spambog.de", "spambox.us", "spamcleaner.org", "spamday.com",
  "spamex.com", "spamfree24.info", "spamfree24.net", "spamgoes.in",
  "spamgourmet.com", "spamhereplease.com", "spamhole.com", "spamify.com",
  "spaminator.de", "spamkill.info", "spaml.com", "spamlot.net",
  "spamobox.com", "spamslicer.com", "spamspot.com", "spamstack.net",
  "spamthis.co.uk", "spamthisplease.com", "spamtrail.com", "spamtroll.net",
  "spamavert.com", "speed.1s.fr", "spoofmail.de", "stop-my-spam.com",
  "suremail.info", "teewars.org", "tempail.com", "tempemail.biz",
  "tempemail.co.za", "tempemail.com", "tempemail.net", "tempinbox.com",
  "tempmail.it", "tempmail.us", "tempmail.win", "tempmail.ws",
  "tempomail.fr", "temporaryemail.net", "temporaryforwarding.com",
  "temporaryinbox.com", "thankyou2010.com", "thisisnotmyrealemail.com",
  "throwaway.email", "throam.com", "trash2009.com", "trash-amil.com",
  "trashdevil.com", "trashmail.at", "trashmail.com", "trashmail.de",
  "trashmail.me", "trashmail.net", "trashmail.org", "trashmailer.com",
  "trashymail.com", "trbvm.com", "tyldd.com", "uggsrock.com", "umail.net",
  "upliftnow.com", "urlslip.com", "v10mail.com", "vipmail.name",
  "vipmail.pw", "vomoto.com", "vpn.st", "walala.org", "webemail.me",
  "weg-werf-email.de", "wh4f.org", "whyspam.me", "wiz2.site", "wmik.net",
  "wn8.in", "wuzup.net", "xagloo.com", "xemaps.com", "xents.com",
  "xing886.uu.gl", "xjoi.com", "xost.xyz", "xoxy.net", "xyzfree.net",
  "yep.it", "yopmail.com", "yopmail.fr", "yopmail.net", "you-spam.com",
  "yuurok.com", "zehnminutenmail.de", "zippymail.info", "zoaxe.com",
  "zoemail.net", "zomg.info", "zxcvbnm.com",
]);

export function isDisposableEmail(email: string): boolean {
  const domain = email.split("@").pop()?.toLowerCase().trim();
  if (!domain) return false;
  return disposableDomains.has(domain);
}
