name: pavagexpert

services:
  pavagexpert:
    container_name: pavagexpert
    image: ghcr.io/shogodel/pavagexpert:latest
    pull_policy: always
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
      - DATA_DIR=/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - jobs_data:/data

volumes:
  jobs_data:
    external: true

networks:
  default:
    external: true
    name: apps_default
