services:
  pavexpert:
    image: ghcr.io/shogodel/pavagexpert:latest
    pull_policy: always
    restart: unless-stopped
    environment:
      - NODE_ENV=production

networks:
  default:
    external: true
    name: apps_default
