services:
  pavexpert:
    image: ghcr.io/shogodel/pavagexpert:latest
    pull_policy: always
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - swag-network

networks:
  swag-network:
    external: true
    name: web
